name = "backend"
compatibility_date = "2024-07-14"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzU1MjgxNmEtMjc5Mi00NGQxLTlkMDEtNDk4ZGE3ZTMyZDMzIiwidGVuYW50X2lkIjoiZDJmZjdhODNjZjJlMGNkYjdhM2IyMzVkYjkyZjBhNGIzMWQxMzMzYWRmMWJiOGM4ZjE0ZDUzZDIzNTk5ZWI4NCIsImludGVybmFsX3NlY3JldCI6ImY4M2RkNDdhLTc2MjEtNDQ5MC05M2E4LTMwM2U3NmViMmY1MCJ9.Luw_zkytG8Z0vOxOGVXovL3JpqeUpRZNKC67ArMZtH4"
JWT_SECRETE="asdfasfdasfas"